// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkqai4UcqDDna_lXyzPnoLo1HMP8tWKss',
    appId: '1:870645092899:web:bf022bfd2429044b915796',
    messagingSenderId: '870645092899',
    projectId: 'todolistapp-b2b1f',
    authDomain: 'todolistapp-b2b1f.firebaseapp.com',
    storageBucket: 'todolistapp-b2b1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUrbxbZqBTmpMUeFg2SSQZMZSiUk7ZLhg',
    appId: '1:870645092899:android:997974aefb6e1ce3915796',
    messagingSenderId: '870645092899',
    projectId: 'todolistapp-b2b1f',
    storageBucket: 'todolistapp-b2b1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSG3J8OravgjnVW9-jZVamqjbSKbddU2w',
    appId: '1:870645092899:ios:96daa2713467194b915796',
    messagingSenderId: '870645092899',
    projectId: 'todolistapp-b2b1f',
    storageBucket: 'todolistapp-b2b1f.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSG3J8OravgjnVW9-jZVamqjbSKbddU2w',
    appId: '1:870645092899:ios:96daa2713467194b915796',
    messagingSenderId: '870645092899',
    projectId: 'todolistapp-b2b1f',
    storageBucket: 'todolistapp-b2b1f.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkqai4UcqDDna_lXyzPnoLo1HMP8tWKss',
    appId: '1:870645092899:web:3c86fe62204ce2ea915796',
    messagingSenderId: '870645092899',
    projectId: 'todolistapp-b2b1f',
    authDomain: 'todolistapp-b2b1f.firebaseapp.com',
    storageBucket: 'todolistapp-b2b1f.appspot.com',
  );
}
